enabled: true
# see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#enum-constant-summary
left-click-blacklist: []
# see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#enum-constant-summary
right-click-blacklist:
  - BOW
  - CROSSBOW
  - EGG
  - SNOWBALL
  - FIRE_CHARGE
  - POTION
  - SPLASH_POTION
  - LINGERING_POTION
  - HONEY_BOTTLE
  - OMINOUS_BOTTLE
  - TRIDENT
  - FIREWORK_ROCKET
  - SHIELD
  - PAINTING
  - ITEM_FRAME
  - GLOW_ITEM_FRAME
block-food-right-click: true
block-block-right-click: true
block-armor-right-click: true
block-bucket-right-click: true

box-display-particle: false
# should the plugin add the player camera's rotation speed to the attack origin
# this has very similar effects to editing wind back
compensate-camera-movement: false
# When the player can trigger sweep or bash,
# a subtitle of arrow (down, left/right) is shown
camera-direction-title: true

double-sneak-threshold-ms: 500
