name: combat
version: '${version}'
main: comfortable_andy.combat.CombatMain
api-version: '1.20'
softdepend:
  - Sentinel
permissions:
  combat.command.use:
    default: op
  combat.command.reload:
    default: op
  combat.command.enable:
    default: op